tissue:
  "Adrenal_gland": 437
  "Bile-duct": 420
  "Bladder": 146
  "Breast": 2351
  "Cervix": 293
  "Colon": 1440
  "Esophagus": 424
  "HeadNeck": 384
  "Kidney": 134
  "Liver": 224
  "Lung": 184
  "Ovarian": 146
  "Pancreatic": 195
  "Prostate": 182
  "Skin": 187
  "Stomach": 146
  "Testis": 196
  "Thyroid": 226
  "Uterus": 186
