output_path: /tmp/pycharm_project_624/preprocessing/patch_extraction/wsi_example/inference
wsi_paths: /tmp/pycharm_project_624/wsi_example/TCGA-V5-A7RE-11A-01-TS1.57401526-EF9E-49AC-8FF6-B4F9652311CE.svs
wsi_filelist: null
wsi_extension: svs
patch_size: 1024
patch_overlap: 6.25
downsample: 1
target_mpp: null
target_mag: 40.0
level: null
context_scales: null
check_resolution: null
processes: 1
overwrite: true
annotation_paths: null
annotation_extension: null
incomplete_annotations: false
label_map_file: null
label_map:
  background: 0
save_only_annotated_patches: false
exclude_classes: []
store_masks: false
overlapping_labels: false
normalize_stains: false
normalization_vector_json: null
adjust_brightness: false
min_intersection_ratio: 0.05
tissue_annotation: null
tissue_annotation_intersection_ratio: 0.05
masked_otsu: false
otsu_annotation: null
filter_patches: false
apply_prefilter: false
log_path: /tmp/pycharm_project_624/preprocessing/patch_extraction/wsi_example/inference
log_level: info
hardware_selection: cucim
wsi_properties: null
